### ISSUE TITLE
API & Webhooks Module: missing some events?

### ISSUE THREAD

**Issue by MacPrawn** [freescout-help-desk/freescout#4141] opened 2024-07-22 13:13 UTC
Hi all!

I'm trying to connect a FreeScout installation to a custom remote application via the API. It seems there may be some events that are not sent out by the API, and I was wondering if there's a reason for the omissions or if they are just things to be added, in which case I offer to submit a PR:

1. If I select conversations from a folder's list (i.e. "Unassigned", "Mine", etc) and then bulk delete all conversations, the API does not send a "convo.deleted" message for any of the deleted conversations. If I go in each conversation individually and click the "Trash" button, that works.
2. Restoring a deleted message does not seem to issue an event? I would expect either a specific "Restore" event? Or at the very least a "conversation.moved" event?
3. When a message is permanently deleted (i.e. not just placed in the "Deleted" folder) there is no event sent out?

Thanks!

**Comment by freescout-help** [comment] 2024-07-22 13:31
1. Fixed in the `master` branch and will be published in the next release.

2. It's by design.  Feel free to [submit a feature request](https://freescout.net/request-feature/).

3. It's by design.  Feel free to [submit a feature request](https://freescout.net/request-feature/).

**Comment by MacPrawn** [comment] 2024-07-23 10:04
Thankl you for your prompt response. Would you mind if I coded #2 and #3 and submitted PRs for them?

**Comment by freescout-help** [comment] 2024-07-23 10:19
Yes, feel free to submit PRs.

**Comment by freescout-help** [comment] 2024-07-23 13:51
"convo.deleted_forever" and "convo.restored" events have been added in API & Webhooks Module v1.0.80. There was no need in extra hooks.

**Closed by freescout-help** 2024-07-23 13:51 UTC

**Comment by MacPrawn** [comment] 2024-07-23 14:36
Thank you but I would argue the event you are using for "convo.deleted_forever" could cause problem: the event "conversation.deleting" is called **before** the conversation is deleted. So if something goes wrong after that call and the conversation ends-up _not_ being deleted in Freescout, third-party apps will potentially already have deleted their data on their end and will be left out of sync.

Is there any way to have an event fire **after** the conversation has successfully been deleted?

**Comment by freescout-help** [comment] 2024-07-23 16:46
Normally conversations are deleted forever via https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L1889

Conversation observer's `deleted()` event is not fired in such cases. The module uses `conversations.before_delete_forever` event. The `conversation.deleting` event is used as backup in case the conversation is not deleted via standard `$conversation->deleteForever()` function.

**Comment by MacPrawn** [comment] 2024-07-23 17:00
Right, ok I see: because you use mass deletion on conversations on https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L1916

Ok, but my point still remains the same: a third-party can only be told that Freescout _intends_ to delete one or more conversations. (through the "conversation.deleting" or "conversations.before_delete_forever" events) There's no way to know that those conversations actually have bene deleted for real and so if something goes wrong after you issued your webhook, you may end up _not_ deleting your copy of one or more conversations and the third-party will have already deleted their copy...

At the very least, could we add a "conversations.after_delete_forever" after 
https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L1918 
Then you use that new event to issue your API module's "convo.deleted_forever" webhook?

It's not perfect, but at least there's less risk of getting de-synchronized...?

**Comment by freescout-help** [comment] 2024-07-23 17:11
> At the very least, could we add a "conversations.after_delete_forever" after
> https://github.com/freescout-help-desk/freescout/blob/dist/app/Conversation.php#L1918
> Then you use that new event to issue your API module's "convo.deleted_forever" webhook?

Unfortunately not. `Conversation::deleteConversationsForever()` deletes conversations without fetching them from DB for performance reasons, so there is no way to pass `$conversation` object to `conversations.after_delete_forever` hook.

**Comment by MacPrawn** [comment] 2024-07-23 17:16
Of course - but like your conversations.before_delete_forever event, you could pass the conversation IDs...

**Comment by freescout-help** [comment] 2024-07-23 18:11
After a conversation is deleted from DB it can't be retrieved from DB by ID to pass it's data to the webhook.

**Comment by MacPrawn** [comment] 2024-07-23 18:16
:) But you already have the ids - you have them in the $conversation_ids variable...
