### ISSUE TITLE
Headers in messages

### ISSUE THREAD

**Issue by Munktells** [freescout-help-desk/freescout#4181] opened 2024-08-15 07:33 UTC
Since a while back ago, Freescout has starting to showing e-mail headers in new messages.
It's shown above the message itself. 
This only happens for some messages, not all.

Any ideas what could be causing this?

PHP version: **8.2.22**
FreeScout version: **1.8.148**
Database: **MySQL**
Are you using CloudFlare: **No**
Are you using non-official modules: **No**

![Headers in new messages](https://github.com/user-attachments/assets/aca88eb6-dfc4-4f83-bb48-c5ba8ffd18de)

**Comment by cruunnerr** [comment] 2024-08-15 11:14
I have exactly the same problem after I updated from 1.8.109 to 1.8.149. 
Like @PysX found out (and i can confirm) this happens only when the content-type of the mail is text/plain
https://github.com/freescout-help-desk/freescout/issues/4155

Unfortunatley the issue was closed without any solution

**Comment by freescout-help** [comment] 2024-08-15 18:58
@Munktells Can you send a sample email (send, not forward) at support@freescout.net. If not - send the EML file of the email.

**Comment by cruunnerr** [comment] 2024-08-19 08:59
I sent you an eml, but unfortunately you were not able to reproduce it. Since i cannot give you access to my freescout server maybe you can try this:

With this python script I am able to reproduce the phenomenon:

```
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

# E-Mail Details
sender_email = "sender@domain.de"
receiver_email = "receiver@domain.de.de"
subject = "0000 Just a test"
body = "Body text message"

# SMTP Server Konfiguration
smtp_server = "mail.domain.de"  # Outlook SMTP Server
smtp_port = 25  # Unverschlüsselter SMTP Port

# Plaintext E-Mail Nachricht erstellen
msg = MIMEText(body, 'plain') # Note this!
msg['From'] = sender_email
msg['To'] = receiver_email
msg['Subject'] = subject

# Verbindung zum SMTP-Server aufbauen und E-Mail senden
try:
    server = smtplib.SMTP(smtp_server, smtp_port)
    server.sendmail(sender_email, receiver_email, msg.as_string())  # E-Mail senden
    print("E-Mail erfolgreich gesendet!")
except Exception as e:
    print(f"Fehler beim Senden der E-Mail: {e}")
finally:
    server.quit()  # Verbindung schließen
```

**Comment by freescout-help** [comment] 2024-08-19 09:19
@cruunnerr Try to send a test email to support@freescout.net using your python script.

**Comment by cruunnerr** [comment] 2024-08-19 09:36
I did right at this moment. thank you

**Comment by freescout-help** [comment] 2024-08-23 08:02
This must be something server specific. We could not reproduce the issue on obtained EML files or real emails. The issue need to be investigated on the server.

**Comment by PysX** [comment] 2024-08-23 09:34
In my case : 

- STMP server is POSTFIX
- Mails are fetched in freescout withPOP3 protocol with user/password authentication
- No SSL/TLS.

**Comment by cruunnerr** [comment] 2024-08-23 10:36
@freescout-help 

In our production system we are using Microsoft exchange and the mails are only send locally. Here is where I can reproduce the issue with the python script posted above.



For further tests I just installed a fresh Ubuntu 22.04 LTS and directly installed freescout with your bash script.
After that I added an email account in freescout which is hosted by ionos.
Mails are fetched in freescout with POP3 protocol with user/password authentication.
No SSL/TLS.

I then added a few more files to the python script and sent a test mail with an ionos account to the fresh installed freescout instance. And that results in exactly that issue.
I used the same script to send a testmail (from an ionos account, too) to your support so I am wondering why the error doesn't appear to you.


```
import smtplib
from email.mime.text import MIMEText
import ssl

# E-Mail Details
sender_email = "xxx@xxx.de"
receiver_email = "support@freescout.net"
subject = "Test subject - Reffering to Github issue #4181"
body = "Test body text. Reffering to Github issue #4181"

# SMTP Server Konfiguration
smtp_server = "smtp.ionos.de"  # SMTP Server
smtp_port = 465  # SMTP Port für TLS
smtp_username = "xxx@xxx.de"
smtp_password = "SUPERSECUREPASSWORD"

# Plaintext E-Mail Nachricht erstellen
msg = MIMEText(body, 'plain')
msg['From'] = sender_email
msg['To'] = receiver_email
msg['Subject'] = subject

try:
    context = ssl.create_default_context()  # SSL/TLS Kontext erstellen
    with smtplib.SMTP_SSL(smtp_server, smtp_port, context=context) as server:
        server.login(smtp_username, smtp_password)  # Anmelden
        server.sendmail(sender_email, receiver_email, msg.as_string())  # E-Mail senden
    print("E-Mail erfolgreich gesendet!")
except Exception as e:
    print(f"Fehler beim Senden der E-Mail: {e}")
finally:
    server.quit()  # Verbindung schließen

```


Maybe some other could try to reproduce or confirm my experience

**Comment by freescout-help** [comment] 2024-08-24 05:53
We've managed to reproduce the issue. It occurs only when POP3 is used.
Related issue: https://github.com/Webklex/php-imap/issues/386

**Comment by freescout-help** [comment] 2024-08-24 10:02
Fixed in the `master` branch and will be published in the next release.

**Comment by PysX** [comment] 2024-08-26 07:45
Thanks for finding an fixing this bug !

**Closed** 2024-08-27 11:52 UTC
