### ISSUE TITLE
Template variables are not substituted in Mailbox From Name when conversation history is enabled

### ISSUE THREAD

**Issue by ohader** [freescout-help-desk/freescout#4169] opened 2024-08-07 10:16 UTC
> PHP version: 8.2.22
> FreeScout version: 1.8.147
> Database: Mysql (10.11.8-MariaDB-ubu2204)
> Are you using CloudFlare: No
> Are you using non-official modules: No

### Problem

Given that `Settings > General > Conversation History` is set to `include the last message`.

Imagine an agent starts a new conversation, the recipient/client did not respond, after a while the agent responds to their own previous conversation with a follow-up message.

The template variables of the previous message do not seem to be substituted correctly.

### Proof

For simplicity, this just shows the `text/plain` mime-parts of the message.
For instance, the template variable `{%user.fullName%}` is not substituted.

```
--_=_swift_1723025067_7b886b817418cc7121fd253c66b6a79d_=_
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

TEST (second message, follow-up)

--

[IN.DIE.musik e.V.]

Oliver Hader

---------------------------------------------------------=
--
## {%user.fullName%} | IN.DIE.musik e.V. Billing, am Aug 7 @ 12:00 (Eu=
rope/Berlin):=20
TEST (first message)

--

[IN.DIE.musik e.V.]

Oliver Hader
=
```

**Comment by freescout-help** [comment] 2024-08-07 11:12
>  template variable {%user.fullName%} is not substituted

Do you mean template variable in the Mailbox Signature? If so we can't reproduce the issue.

**Comment by ohader** [comment] 2024-08-08 11:29
In the case mentioned above, the variable `{%user.fullName%}` stems from a custom from name header (defined in mailbox settings).

<img width="506" alt="Screenshot 2024-08-08 at 13 28 11" src="https://github.com/user-attachments/assets/29b2fc9a-09b0-4279-ac83-59544944371f">

**Comment by freescout-help** [comment] 2024-08-08 12:00
Fixed in the `master` branch and will be published in the next release.

**Closed** 2024-08-14 16:55 UTC
